# Generated by Django 5.2.11 on 2026-03-03 16:29

import django.db.models.deletion
import pkgutil

import hordak.migrations as hordak_migrations
from django.conf import settings
from django.db import migrations, models


def _latest_hordak_0055_migration() -> str | None:
    migration_names = sorted(
        module_info.name
        for module_info in pkgutil.iter_modules(hordak_migrations.__path__)
        if module_info.name.startswith("0055_")
    )
    if not migration_names:
        return None
    canonical_name = "0055_alter_leg_credit_alter_leg_currency_alter_leg_debit"
    return canonical_name if canonical_name in migration_names else migration_names[-1]


HORDAK_TARGET_MIGRATION = _latest_hordak_0055_migration() or "0054_check_debit_credit_positive"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hordak", HORDAK_TARGET_MIGRATION),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAccountVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_visibility_overrides",
                        to="hordak.account",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_visibility_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["teacher", "account"], name="accounts_te_teacher_96fc12_idx"
                    )
                ],
                "unique_together": {("teacher", "account")},
            },
        ),
    ]
