# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="teacheraccountvisibility",
            name="accounts_te_teacher_96fc12_idx",
        ),
        migrations.AddIndex(
            model_name="teacheraccountvisibility",
            index=models.Index(
                fields=["teacher", "is_visible", "account"],
                name="accounts_te_teacher_vis_ac_idx",
            ),
        ),
    ]
