# Generated by Django 5.2.11 on 2026-03-03 12:04

import django.db.models.deletion
import pkgutil

import hordak.migrations as hordak_migrations
from django.conf import settings
from django.db import migrations, models


def _latest_hordak_0055_migration() -> str | None:
    migration_names = sorted(
        module_info.name
        for module_info in pkgutil.iter_modules(hordak_migrations.__path__)
        if module_info.name.startswith("0055_")
    )
    if not migration_names:
        return None
    canonical_name = "0055_alter_leg_credit_alter_leg_currency_alter_leg_debit"
    return canonical_name if canonical_name in migration_names else migration_names[-1]


HORDAK_TARGET_MIGRATION = _latest_hordak_0055_migration() or "0054_check_debit_credit_positive"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_post_hordak_0055_recreate_views"),
        ("hordak", HORDAK_TARGET_MIGRATION),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_number",
                    models.PositiveIntegerField(
                        help_text="Correlativo por empresa, asignado automáticamente.",
                        verbose_name="número de asiento",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                ("description", models.CharField(max_length=500, verbose_name="descripción")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("INVOICE", "Factura"),
                            ("RECEIPT", "Recibo"),
                            ("OTHER", "Otro"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text='Ej.: "Factura A-0001", "Recibo 00123".',
                        max_length=100,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entry",
                        to="hordak.transaction",
                        verbose_name="transacción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento contable",
                "verbose_name_plural": "Asientos contables",
                "ordering": ["company", "entry_number"],
                "unique_together": {("company", "entry_number")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEBIT", "Deudora"), ("CREDIT", "Acreedora")],
                        max_length=6,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, verbose_name="importe"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hordak.account",
                        verbose_name="cuenta",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="journal.journalentry",
                        verbose_name="asiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de asiento",
                "verbose_name_plural": "Líneas de asiento",
            },
        ),
    ]
