# Generated by Django 5.2.11 on 2026-03-03 15:40

import django.db.models.deletion
import pkgutil

import hordak.migrations as hordak_migrations
from django.conf import settings
from django.db import migrations, models


def _latest_hordak_0055_migration() -> str | None:
    migration_names = sorted(
        module_info.name
        for module_info in pkgutil.iter_modules(hordak_migrations.__path__)
        if module_info.name.startswith("0055_")
    )
    if not migration_names:
        return None
    canonical_name = "0055_alter_leg_credit_alter_leg_currency_alter_leg_debit"
    return canonical_name if canonical_name in migration_names else migration_names[-1]


HORDAK_TARGET_MIGRATION = _latest_hordak_0055_migration() or "0054_check_debit_credit_positive"


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_books_closed_until"),
        ("hordak", HORDAK_TARGET_MIGRATION),
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="journal.journalentry",
                verbose_name="reversión de",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["company", "date"], name="journal_jou_company_ff69d3_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["journal_entry", "account", "type"], name="journal_jou_journal_04542b_idx"
            ),
        ),
    ]
