# Generated by Django 5.2.11 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_journalentry_reversal_of_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="journalentry",
            name="journal_jou_company_ff69d3_idx",
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company", "date", "entry_number"],
                name="journal_entry_cmp_dt_no_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["date", "entry_number"],
                name="journal_entry_dt_no_idx",
            ),
        ),
        migrations.RemoveIndex(
            model_name="journalentryline",
            name="journal_jou_journal_04542b_idx",
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["journal_entry", "account", "type"],
                name="journal_line_je_ac_tp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["account", "journal_entry"],
                name="journal_line_ac_je_idx",
            ),
        ),
    ]
